apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ssm-demo33a
  janus-idp.io/tekton: ssm-demo33a
  backstage.io/kubernetes-id: ssm-demo33a
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ssm-demo33a
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
